spring:
  application:
    name: currency-conversion-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8100

#forex-service:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka